import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import QueryProvider from '@/provider/queryProvider'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const queryClient = new QueryClient()
  return (
    <html lang="en">
      
         <body className={inter.className}>
            <QueryProvider>
              {children}
            </QueryProvider>
          </body>
      
    </html>
  )
}
